name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  tests:
    name: CI
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [stable]
        target:
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - i686-pc-windows-msvc
          - i686-pc-windows-gnu
        include:
          - channel: stable
            target: x86_64-pc-windows-msvc
            lint: true

    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v2
      - name: Install rust-${{ matrix.channel }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          profile: minimal
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.channel }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.channel }}
      - name: Create Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Check formatting
        if: matrix.lint
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Lint
        if: matrix.lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets
      - name: Run tests (no features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --release --no-fail-fast --no-default-features
      - name: Run tests (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --release --no-fail-fast --all-features

  semver:
    name: Check semver
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: obi1kenobi/cargo-semver-checks-action@v2
